In [1]:
import numpy as np

In [2]:
#Create a numpy array
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#dimension
arr1.ndim

2

In [4]:
#shape
arr1.shape

(3, 3)

In [5]:
arr1.size

9

In [6]:
type(arr1)

numpy.ndarray

In [8]:
arr1.dtype

dtype('int32')

In [9]:
arr1 = np.array(((1,2,3),(4,5,6),(7,8,9)))
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr2 = np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr2 = np.ones((2,3,4))
arr2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
arr2.ndim

3

In [14]:
arr3 = np.ones((2,2,3,4))
arr3
arr3.ndim

4

In [15]:
arr4 = np.random.random((3,3))
arr4

array([[0.61421968, 0.0475258 , 0.30949434],
       [0.94970079, 0.47174004, 0.89780777],
       [0.57550626, 0.09922948, 0.63015399]])

In [16]:
arr5 = np.arange(0,10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr5.ndim

1

In [18]:
arr6 = np.arange(1,25).reshape(2,3,4)
arr6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [19]:
arr6.ndim

3

In [22]:
arr7 = arr6.reshape(2,12)
arr7

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [24]:
arr8 = np.linspace(0,5,10)
arr8

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
arr9 = np.linspace(0,1,100).reshape(10,10)
arr9

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

In [28]:
arr10 = np.linspace(0,1,100).reshape(2,5,10)
arr10

array([[[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
         0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
        [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
         0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
        [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
         0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
        [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
         0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
        [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
         0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949]],

       [[0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
         0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
        [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
         0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
        [0.70707071, 0.71

In [29]:
arr8

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [33]:
arr10 = np.arange(0,20).reshape(4,5)
arr10

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
flat = arr10.flatten()
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
np.exp(flat)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [36]:
flat_inv = 1/flat
flat_inv

c:\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [38]:
np.isinf(flat_inv)

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [39]:
arr1 = np.arange(1,25).reshape(2,3,4)
arr2 = np.arange(1,25).reshape(2,3,4)

In [40]:
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [41]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [42]:
arr1 + arr2

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]],

       [[26, 28, 30, 32],
        [34, 36, 38, 40],
        [42, 44, 46, 48]]])

In [44]:
arr3 = np.arange(1,13).reshape(3,4)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
arr1 + arr3

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]],

       [[14, 16, 18, 20],
        [22, 24, 26, 28],
        [30, 32, 34, 36]]])

In [46]:
arr1 + 10

array([[[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]],

       [[23, 24, 25, 26],
        [27, 28, 29, 30],
        [31, 32, 33, 34]]])

In [47]:
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [48]:
arr1[0,0,1]

2

In [50]:
arr1[1,0,1]

14

In [51]:
arr1[0,2,3]

12

In [52]:
arr1[1,1,3]

20

In [53]:
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [55]:
arr1[0,:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
arr1[:,1,:]

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [57]:
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [58]:
arr1[0,1:3,2:4]

array([[ 7,  8],
       [11, 12]])

In [62]:
N = 10000000

In [63]:
%%time
l1 = list(range(N))
for i in range(N):
    l1[i] = l1[i] * l1[i]

Wall time: 11.2 s


In [64]:
%%time
l1 = list(range(N))
l1 = [x*x for x in l1]

Wall time: 4.93 s


In [65]:
%%time
l1 = list(range(N))
l1 = map(lambda x:x*x, l1)

Wall time: 783 ms


In [66]:
%%time 
arr = np.arange(N)
arr =  arr * arr

Wall time: 204 ms


In [69]:
%%time
np.mean(arr)

Wall time: 31 ms


1724754.9629376

In [70]:
arr % 2 == 0

array([ True, False,  True, ..., False,  True, False])

In [73]:
arr[(arr % 2 == 0) & (arr>100)]

array([      144,       196,       256, ..., 156447268, 196447248,
       236447236])

In [74]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])